name: Unit Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # Label of the container job
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests.
      - name: Check out repository code
        uses: actions/checkout@v3
        working-directory: my-app
      - uses: actions/setup-node@v3
        working-directory: my-app
        with:
          node-version: "lts/*"

      - name: Install dependencies
        working-directory: my-app
        run: npm ci

      - name: Run unit  tests
        working-directory: my-app
        run: npm run test
